#!/usr/bin/env bash

HOLY_COPY="holy you <command>"
HOLY_GOAL=DOTS_HOME
HOLY_HERE=~/.bashrc

# $ holy one on # true
. $(holy one path init)/once.sh

tee -a $HOLY_HERE > /dev/null << END

. "\$$HOLY_GOAL"/source.sh
END
